import React, { useEffect, useState } from "react";
import { api, formatApiErrorDetail } from "@/lib/api";
import { PageHeader } from "@/components/Terminal";
import { Button } from "@/components/ui/button";
import { Sparkles, RefreshCw } from "lucide-react";
import { toast } from "sonner";

function renderMarkdown(text) {
  if (!text) return null;
  const lines = text.split("\n");
  return lines.map((line, i) => {
    const l = line.trim();
    if (l.startsWith("## ")) {
      return (
        <h3 key={i} className="text-terminal-amber uppercase tracking-widest text-xs mt-6 mb-2 font-semibold border-b border-terminal-border pb-1">
          {l.slice(3)}
        </h3>
      );
    }
    if (l.startsWith("# ")) {
      return <h2 key={i} className="text-lg font-bold mt-4">{l.slice(2)}</h2>;
    }
    if (l.startsWith("- ") || l.startsWith("* ")) {
      return (
        <div key={i} className="pl-4 relative text-sm text-terminal-text mb-1 leading-relaxed">
          <span className="absolute left-0 text-terminal-cyan">›</span>
          {l.slice(2)}
        </div>
      );
    }
    if (!l) return <div key={i} className="h-2" />;
    return <p key={i} className="text-sm text-terminal-text mb-2 leading-relaxed">{l}</p>;
  });
}

export default function Insights() {
  const [item, setItem] = useState(null);
  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(true);

  useEffect(() => {
    api.get("/ai/insights").then(({ data }) => setItem(data)).finally(() => setFetching(false));
  }, []);

  const generate = async () => {
    setLoading(true);
    try {
      const { data } = await api.post("/ai/insights");
      setItem(data);
      toast.success("Fresh insights generated by Claude Sonnet 4.5.");
    } catch (e) {
      toast.error(formatApiErrorDetail(e.response?.data?.detail) || e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <PageHeader
        title="AI Insights"
        subtitle="Claude Sonnet 4.5 · performance review across your trade history."
        right={
          <Button data-testid="generate-insights" onClick={generate} disabled={loading}
                  className="rounded-none bg-amber-950 text-terminal-amber border border-amber-800 hover:bg-amber-900 uppercase tracking-widest">
            {loading ? <RefreshCw className="w-4 h-4 mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 mr-2" />}
            {loading ? "Analyzing..." : item ? "Regenerate" : "Generate insights"}
          </Button>
        }
      />
      <div className="p-6">
        <div className="border border-terminal-border bg-terminal-panel">
          <div className="px-5 py-3 border-b border-terminal-border flex items-center justify-between">
            <div className="text-xs uppercase tracking-widest text-terminal-mute">// Performance review</div>
            {item?.created_at && (
              <div className="text-[10px] font-mono-num text-terminal-dim uppercase tracking-widest">
                {new Date(item.created_at).toLocaleString()} · {item.trade_count} trades
              </div>
            )}
          </div>
          <div className="p-6 min-h-[400px]">
            {fetching && <div className="text-terminal-mute font-mono-num">LOADING...</div>}
            {!fetching && !item && (
              <div className="text-terminal-mute max-w-2xl">
                <div className="text-terminal-amber uppercase tracking-widest text-xs mb-2">// Awaiting analysis</div>
                <p className="text-sm">
                  Log at least a few trades, then click <span className="text-terminal-amber">Generate insights</span> to get
                  a structured performance review from Claude Sonnet 4.5: strengths, leaks, pattern findings, and next steps.
                </p>
              </div>
            )}
            {item && renderMarkdown(item.text)}
          </div>
        </div>
      </div>
    </div>
  );
}
